apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-name
spec:
  entrypoint: entry
  - name: entry
    dag:
      tasks:
      - name: first
        templateRef:
          name: block1212
          template: whalesay-template
        arguments:
          parameters:
          - name: message
            value: "{{workflow.parameters.first-message}}"
