apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-whalesay-template
spec:
  entrypoint: whalesay-template
  templates:
  - name: template-name
  arguments:
    parameters:
    - name: 
    inputs: 
      parameters: 
      - name: message
        value: test
      - name: inputname
    container:
      image: docker/whalesay
      command: [cowsay]
  - name: test-name
    suspend:
      duration: "20s"
  - name: some-script
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random

        i = random.randint(1, 100)

        print(i)
