apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-whalesay-template
spec:
  entrypoint: whalesay-template
  templates:
  - name: template-name
    inputs: 
      parameters: 
      - name: message
        value: test
    container:
      image: docker/whalesay
      command: [cowsay]
